version: '3.9'
services:
  db:
    image: mariadb:10.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DB_NAME}
      - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER_NAME}
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
  nest-project:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "3003:3003"
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
      - db
    env_file: .env
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
      - PORT=${PORT}
      - MYSQL_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DB_NAME=${MYSQL_DB_NAME}
      - MYSQL_USER_NAME=${MYSQL_USER_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - API_HOST=${API_HOST}
  redis:
    image: redis
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
volumes:
  mysql:
    driver: local
